// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// StworzeniePizzy - Use 'StworzeniePizzyParams' to pass parameters into this method.
        /// </summary>
        public void StworzeniePizzy()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIMSNPolskaOutlookSkypWindow.UIHomePagePizzaManagerDocument.UIItemCustom;
            HtmlEdit uINazwaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UINazwaEdit;
            HtmlEdit uICenaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UICenaEdit;
            HtmlComboBox uIDodatekComboBox = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIDodatekComboBox;
            HtmlButton uIZapiszButton = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIZapiszButton;
            #endregion

            // Go to web page 'http://localhost:61811/' using new browser instance
            this.UIMSNPolskaOutlookSkypWindow.LaunchUrl(new System.Uri(this.StworzeniePizzyParams.UIMSNPolskaOutlookSkypWindowUrl));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(60, 5));

            // Type 'DobraPizza' in 'Nazwa' text box
            uINazwaEdit.Text = this.StworzeniePizzyParams.UINazwaEditText;

            // Type '15' in 'Cena' text box
            uICenaEdit.Text = this.StworzeniePizzyParams.UICenaEditText;

            // Select 'Cebula' in 'Dodatek' combo box
            uIDodatekComboBox.SelectedItem = this.StworzeniePizzyParams.UIDodatekComboBoxSelectedItem;

            // Click 'Zapisz' button
            Mouse.Click(uIZapiszButton, new Point(12, 17));
        }
        
        /// <summary>
        /// StworzeniePizzy1 - Use 'StworzeniePizzy1Params' to pass parameters into this method.
        /// </summary>
        public void StworzeniePizzy1()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIMSNPolskaOutlookSkypWindow.UIHomePagePizzaManagerDocument.UIItemCustom;
            HtmlEdit uINazwaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UINazwaEdit;
            HtmlEdit uICenaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UICenaEdit;
            HtmlComboBox uIDodatekComboBox = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIDodatekComboBox;
            HtmlButton uIZapiszButton = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIZapiszButton;
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            HtmlHyperlink uIStwórzpizzeHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIHomePagePizzaManagerDocument.UIStwórzpizzeHyperlink;
            #endregion

            // Go to web page 'http://localhost:61811/' using new browser instance
            this.UIMSNPolskaOutlookSkypWindow.LaunchUrl(new System.Uri(this.StworzeniePizzy1Params.UIMSNPolskaOutlookSkypWindowUrl));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(60, 5));

            // Type 'DobraPizza' in 'Nazwa' text box
            uINazwaEdit.Text = this.StworzeniePizzy1Params.UINazwaEditText;

            // Type '15' in 'Cena' text box
            uICenaEdit.Text = this.StworzeniePizzy1Params.UICenaEditText;

            // Select 'Cebula' in 'Dodatek' combo box
            uIDodatekComboBox.SelectedItem = this.StworzeniePizzy1Params.UIDodatekComboBoxSelectedItem;

            // Click 'Zapisz' button
            Mouse.Click(uIZapiszButton, new Point(12, 17));

            // Go to web page 'http://localhost:61811/'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.StworzeniePizzy1Params.UIMSNPolskaOutlookSkypWindowUrl1));

            // Click 'Stwórz pizze ⊕' link
            Mouse.Click(uIStwórzpizzeHyperlink, new Point(90, 29));

            // Type 'NowaPizza' in 'Nazwa' text box
            uINazwaEdit.Text = this.StworzeniePizzy1Params.UINazwaEditText1;

            // Type '15' in 'Cena' text box
            uICenaEdit.Text = this.StworzeniePizzy1Params.UICenaEditText1;

            // Select 'Cebula' in 'Dodatek' combo box
            uIDodatekComboBox.SelectedItem = this.StworzeniePizzy1Params.UIDodatekComboBoxSelectedItem1;

            // Click 'Zapisz' button
            Mouse.Click(uIZapiszButton, new Point(46, 19));
        }
        
        /// <summary>
        /// AddingAddonAndDeletingIt - Use 'AddingAddonAndDeletingItParams' to pass parameters into this method.
        /// </summary>
        public void AddingAddonAndDeletingIt()
        {
            #region Variable Declarations
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            HtmlHyperlink uIStwórznowydodatekHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument.UIStwórznowydodatekHyperlink;
            HtmlEdit uINazwaEdit = this.UIMSNPolskaOutlookSkypWindow.UIDodatekFormPizzaManaDocument.UINazwaEdit;
            HtmlButton uIStwórzButton = this.UIMSNPolskaOutlookSkypWindow.UIDodatekFormPizzaManaDocument.UIStwórzButton;
            HtmlHyperlink uIDeleteHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument1.UIDeleteHyperlink;
            #endregion

            // Go to web page 'http://localhost:61811/dodatek'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.AddingAddonAndDeletingItParams.UIMSNPolskaOutlookSkypWindowUrl));

            // Click 'Stwórz nowy dodatek ⊛' link
            Mouse.Click(uIStwórznowydodatekHyperlink, new Point(51, 28));

            // Type 'nowydodatek' in 'Nazwa' text box
            uINazwaEdit.Text = this.AddingAddonAndDeletingItParams.UINazwaEditText;

            // Click 'Stwórz ⊛' button
            Mouse.Click(uIStwórzButton, new Point(95, 57));

            // Go to web page 'http://localhost:61811/Dodatek/'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.AddingAddonAndDeletingItParams.UIMSNPolskaOutlookSkypWindowUrl1));

            // Click 'Delete' link
            Mouse.Click(uIDeleteHyperlink, new Point(30, 8));
        }
        
        /// <summary>
        /// CheckingAllSubSites - Use 'CheckingAllSubSitesParams' to pass parameters into this method.
        /// </summary>
        public void CheckingAllSubSites()
        {
            #region Variable Declarations
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            HtmlHyperlink uIPizzaManagerHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIHomePagePizzaManagerDocument.UIPizzaManagerHyperlink;
            HtmlHyperlink uIKontaktHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIHomePagePizzaManagerDocument.UIKontaktHyperlink;
            HtmlHyperlink uIAboutHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIContactPizzaManagerDocument.UIAboutHyperlink;
            HtmlHyperlink uITwojePizzeHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIAboutPizzaManagerDocument.UITwojePizzeHyperlink;
            HtmlHyperlink uIRegisterHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument2.UIRegisterHyperlink;
            HtmlHyperlink uILoginHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIRegisterPizzaManagerDocument.UILoginHyperlink;
            #endregion

            // Go to web page 'http://localhost:61811/'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.CheckingAllSubSitesParams.UIMSNPolskaOutlookSkypWindowUrl));

            // Click 'Pizza Manager' link
            Mouse.Click(uIPizzaManagerHyperlink, new Point(53, 33));

            // Click 'Kontakt' link
            Mouse.Click(uIKontaktHyperlink, new Point(52, 22));

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(51, 26));

            // Click 'Twoje Pizze' link
            Mouse.Click(uITwojePizzeHyperlink, new Point(50, 25));

            // Click 'Register' link
            Mouse.Click(uIRegisterHyperlink, new Point(63, 21));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(41, 27));
        }
        
        /// <summary>
        /// CheckingPizza - Use 'CheckingPizzaParams' to pass parameters into this method.
        /// </summary>
        public void CheckingPizza()
        {
            #region Variable Declarations
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            HtmlHyperlink uICarbonAraHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument2.UICarbonAraHyperlink;
            #endregion

            // Go to web page 'http://localhost:61811/Pizza'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.CheckingPizzaParams.UIMSNPolskaOutlookSkypWindowUrl));

            // Click 'CarbonAra' link
            Mouse.Click(uICarbonAraHyperlink, new Point(31, 10));
        }
        
        /// <summary>
        /// CreatingPizzaAndCheckingIt - Use 'CreatingPizzaAndCheckingItParams' to pass parameters into this method.
        /// </summary>
        public void CreatingPizzaAndCheckingIt()
        {
            #region Variable Declarations
            HtmlHyperlink uITwojePizzeHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIDetailsPizzaManagerDocument.UITwojePizzeHyperlink;
            HtmlCustom uIItemCustom = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument2.UIItemCustom;
            HtmlEdit uINazwaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UINazwaEdit;
            HtmlEdit uICenaEdit = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UICenaEdit;
            HtmlComboBox uIDodatekComboBox = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIDodatekComboBox;
            HtmlButton uIZapiszButton = this.UIMSNPolskaOutlookSkypWindow.UIPizzaManagerPizzaManDocument.UIZapiszButton;
            HtmlHyperlink uIPizzaHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIIndexPizzaManagerDocument2.UIPizzaHyperlink;
            #endregion

            // Click 'Twoje Pizze' link
            Mouse.Click(uITwojePizzeHyperlink, new Point(37, 17));

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(32, 8));

            // Type 'pizza' in 'Nazwa' text box
            uINazwaEdit.Text = this.CreatingPizzaAndCheckingItParams.UINazwaEditText;

            // Type '10' in 'Cena' text box
            uICenaEdit.Text = this.CreatingPizzaAndCheckingItParams.UICenaEditText;

            // Select 'Oliwki' in 'Dodatek' combo box
            uIDodatekComboBox.SelectedItem = this.CreatingPizzaAndCheckingItParams.UIDodatekComboBoxSelectedItem;

            // Click 'Zapisz' button
            Mouse.Click(uIZapiszButton, new Point(42, 16));

            // Click 'pizza' link
            Mouse.Click(uIPizzaHyperlink, new Point(14, 10));
        }
        
        #region Properties
        public virtual StworzeniePizzyParams StworzeniePizzyParams
        {
            get
            {
                if ((this.mStworzeniePizzyParams == null))
                {
                    this.mStworzeniePizzyParams = new StworzeniePizzyParams();
                }
                return this.mStworzeniePizzyParams;
            }
        }
        
        public virtual StworzeniePizzy1Params StworzeniePizzy1Params
        {
            get
            {
                if ((this.mStworzeniePizzy1Params == null))
                {
                    this.mStworzeniePizzy1Params = new StworzeniePizzy1Params();
                }
                return this.mStworzeniePizzy1Params;
            }
        }
        
        public virtual AddingAddonAndDeletingItParams AddingAddonAndDeletingItParams
        {
            get
            {
                if ((this.mAddingAddonAndDeletingItParams == null))
                {
                    this.mAddingAddonAndDeletingItParams = new AddingAddonAndDeletingItParams();
                }
                return this.mAddingAddonAndDeletingItParams;
            }
        }
        
        public virtual CheckingAllSubSitesParams CheckingAllSubSitesParams
        {
            get
            {
                if ((this.mCheckingAllSubSitesParams == null))
                {
                    this.mCheckingAllSubSitesParams = new CheckingAllSubSitesParams();
                }
                return this.mCheckingAllSubSitesParams;
            }
        }
        
        public virtual CheckingPizzaParams CheckingPizzaParams
        {
            get
            {
                if ((this.mCheckingPizzaParams == null))
                {
                    this.mCheckingPizzaParams = new CheckingPizzaParams();
                }
                return this.mCheckingPizzaParams;
            }
        }
        
        public virtual CreatingPizzaAndCheckingItParams CreatingPizzaAndCheckingItParams
        {
            get
            {
                if ((this.mCreatingPizzaAndCheckingItParams == null))
                {
                    this.mCreatingPizzaAndCheckingItParams = new CreatingPizzaAndCheckingItParams();
                }
                return this.mCreatingPizzaAndCheckingItParams;
            }
        }
        
        public UIMSNPolskaOutlookSkypWindow UIMSNPolskaOutlookSkypWindow
        {
            get
            {
                if ((this.mUIMSNPolskaOutlookSkypWindow == null))
                {
                    this.mUIMSNPolskaOutlookSkypWindow = new UIMSNPolskaOutlookSkypWindow();
                }
                return this.mUIMSNPolskaOutlookSkypWindow;
            }
        }
        #endregion
        
        #region Fields
        private StworzeniePizzyParams mStworzeniePizzyParams;
        
        private StworzeniePizzy1Params mStworzeniePizzy1Params;
        
        private AddingAddonAndDeletingItParams mAddingAddonAndDeletingItParams;
        
        private CheckingAllSubSitesParams mCheckingAllSubSitesParams;
        
        private CheckingPizzaParams mCheckingPizzaParams;
        
        private CreatingPizzaAndCheckingItParams mCreatingPizzaAndCheckingItParams;
        
        private UIMSNPolskaOutlookSkypWindow mUIMSNPolskaOutlookSkypWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StworzeniePizzy'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class StworzeniePizzyParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:61811/' using new browser instance
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:61811/";
        
        /// <summary>
        /// Type 'DobraPizza' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "DobraPizza";
        
        /// <summary>
        /// Type '15' in 'Cena' text box
        /// </summary>
        public string UICenaEditText = "15";
        
        /// <summary>
        /// Select 'Cebula' in 'Dodatek' combo box
        /// </summary>
        public string UIDodatekComboBoxSelectedItem = "Cebula";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'StworzeniePizzy1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class StworzeniePizzy1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:61811/' using new browser instance
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:61811/";
        
        /// <summary>
        /// Type 'DobraPizza' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "DobraPizza";
        
        /// <summary>
        /// Type '15' in 'Cena' text box
        /// </summary>
        public string UICenaEditText = "15";
        
        /// <summary>
        /// Select 'Cebula' in 'Dodatek' combo box
        /// </summary>
        public string UIDodatekComboBoxSelectedItem = "Cebula";
        
        /// <summary>
        /// Go to web page 'http://localhost:61811/'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl1 = "http://localhost:61811/";
        
        /// <summary>
        /// Type 'NowaPizza' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText1 = "NowaPizza";
        
        /// <summary>
        /// Type '15' in 'Cena' text box
        /// </summary>
        public string UICenaEditText1 = "15";
        
        /// <summary>
        /// Select 'Cebula' in 'Dodatek' combo box
        /// </summary>
        public string UIDodatekComboBoxSelectedItem1 = "Cebula";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddingAddonAndDeletingIt'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AddingAddonAndDeletingItParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:61811/dodatek'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:61811/dodatek";
        
        /// <summary>
        /// Type 'nowydodatek' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "nowydodatek";
        
        /// <summary>
        /// Go to web page 'http://localhost:61811/Dodatek/'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl1 = "http://localhost:61811/Dodatek/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckingAllSubSites'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckingAllSubSitesParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:61811/'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:61811/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckingPizza'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckingPizzaParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:61811/Pizza'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://localhost:61811/Pizza";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreatingPizzaAndCheckingIt'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreatingPizzaAndCheckingItParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'pizza' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "pizza";
        
        /// <summary>
        /// Type '10' in 'Cena' text box
        /// </summary>
        public string UICenaEditText = "10";
        
        /// <summary>
        /// Select 'Oliwki' in 'Dodatek' combo box
        /// </summary>
        public string UIDodatekComboBoxSelectedItem = "Oliwki";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNPolskaOutlookSkypWindow : BrowserWindow
    {
        
        public UIMSNPolskaOutlookSkypWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                "ve";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                    "ve");
            this.WindowTitles.Add("http://localhost:61811/");
            this.WindowTitles.Add("Home Page - Pizza Manager");
            this.WindowTitles.Add("PizzaManager - Pizza Manager");
            this.WindowTitles.Add("http://go.microsoft.com/fwlink/p/?LinkId=620947&OCID=AVRES000");
            this.WindowTitles.Add("Index - Pizza Manager");
            this.WindowTitles.Add("DodatekForm - Pizza Manager");
            this.WindowTitles.Add("http://localhost:61811/Dodatek/");
            this.WindowTitles.Add("Contact - Pizza Manager");
            this.WindowTitles.Add("About - Pizza Manager");
            this.WindowTitles.Add("Register - Pizza Manager");
            this.WindowTitles.Add("http://localhost:61811/Pizza");
            this.WindowTitles.Add("Details - Pizza Manager");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePagePizzaManagerDocument UIHomePagePizzaManagerDocument
        {
            get
            {
                if ((this.mUIHomePagePizzaManagerDocument == null))
                {
                    this.mUIHomePagePizzaManagerDocument = new UIHomePagePizzaManagerDocument(this);
                }
                return this.mUIHomePagePizzaManagerDocument;
            }
        }
        
        public UIPizzaManagerPizzaManDocument UIPizzaManagerPizzaManDocument
        {
            get
            {
                if ((this.mUIPizzaManagerPizzaManDocument == null))
                {
                    this.mUIPizzaManagerPizzaManDocument = new UIPizzaManagerPizzaManDocument(this);
                }
                return this.mUIPizzaManagerPizzaManDocument;
            }
        }
        
        public UIIndexPizzaManagerDocument UIIndexPizzaManagerDocument
        {
            get
            {
                if ((this.mUIIndexPizzaManagerDocument == null))
                {
                    this.mUIIndexPizzaManagerDocument = new UIIndexPizzaManagerDocument(this);
                }
                return this.mUIIndexPizzaManagerDocument;
            }
        }
        
        public UIDodatekFormPizzaManaDocument UIDodatekFormPizzaManaDocument
        {
            get
            {
                if ((this.mUIDodatekFormPizzaManaDocument == null))
                {
                    this.mUIDodatekFormPizzaManaDocument = new UIDodatekFormPizzaManaDocument(this);
                }
                return this.mUIDodatekFormPizzaManaDocument;
            }
        }
        
        public UIIndexPizzaManagerDocument1 UIIndexPizzaManagerDocument1
        {
            get
            {
                if ((this.mUIIndexPizzaManagerDocument1 == null))
                {
                    this.mUIIndexPizzaManagerDocument1 = new UIIndexPizzaManagerDocument1(this);
                }
                return this.mUIIndexPizzaManagerDocument1;
            }
        }
        
        public UIContactPizzaManagerDocument UIContactPizzaManagerDocument
        {
            get
            {
                if ((this.mUIContactPizzaManagerDocument == null))
                {
                    this.mUIContactPizzaManagerDocument = new UIContactPizzaManagerDocument(this);
                }
                return this.mUIContactPizzaManagerDocument;
            }
        }
        
        public UIAboutPizzaManagerDocument UIAboutPizzaManagerDocument
        {
            get
            {
                if ((this.mUIAboutPizzaManagerDocument == null))
                {
                    this.mUIAboutPizzaManagerDocument = new UIAboutPizzaManagerDocument(this);
                }
                return this.mUIAboutPizzaManagerDocument;
            }
        }
        
        public UIIndexPizzaManagerDocument2 UIIndexPizzaManagerDocument2
        {
            get
            {
                if ((this.mUIIndexPizzaManagerDocument2 == null))
                {
                    this.mUIIndexPizzaManagerDocument2 = new UIIndexPizzaManagerDocument2(this);
                }
                return this.mUIIndexPizzaManagerDocument2;
            }
        }
        
        public UIRegisterPizzaManagerDocument UIRegisterPizzaManagerDocument
        {
            get
            {
                if ((this.mUIRegisterPizzaManagerDocument == null))
                {
                    this.mUIRegisterPizzaManagerDocument = new UIRegisterPizzaManagerDocument(this);
                }
                return this.mUIRegisterPizzaManagerDocument;
            }
        }
        
        public UIDetailsPizzaManagerDocument UIDetailsPizzaManagerDocument
        {
            get
            {
                if ((this.mUIDetailsPizzaManagerDocument == null))
                {
                    this.mUIDetailsPizzaManagerDocument = new UIDetailsPizzaManagerDocument(this);
                }
                return this.mUIDetailsPizzaManagerDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePagePizzaManagerDocument mUIHomePagePizzaManagerDocument;
        
        private UIPizzaManagerPizzaManDocument mUIPizzaManagerPizzaManDocument;
        
        private UIIndexPizzaManagerDocument mUIIndexPizzaManagerDocument;
        
        private UIDodatekFormPizzaManaDocument mUIDodatekFormPizzaManaDocument;
        
        private UIIndexPizzaManagerDocument1 mUIIndexPizzaManagerDocument1;
        
        private UIContactPizzaManagerDocument mUIContactPizzaManagerDocument;
        
        private UIAboutPizzaManagerDocument mUIAboutPizzaManagerDocument;
        
        private UIIndexPizzaManagerDocument2 mUIIndexPizzaManagerDocument2;
        
        private UIRegisterPizzaManagerDocument mUIRegisterPizzaManagerDocument;
        
        private UIDetailsPizzaManagerDocument mUIDetailsPizzaManagerDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePagePizzaManagerDocument : HtmlDocument
    {
        
        public UIHomePagePizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/";
            this.WindowTitles.Add("Home Page - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "h";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Home Page - Pizza Manager");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UIStwórzpizzeHyperlink
        {
            get
            {
                if ((this.mUIStwórzpizzeHyperlink == null))
                {
                    this.mUIStwórzpizzeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIStwórzpizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIStwórzpizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIStwórzpizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIStwórzpizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Stwórz pizze ⊕ ";
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pizza/New";
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Pizza/New";
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-warning";
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-warning\" href=\"/Pizza/New";
                    this.mUIStwórzpizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIStwórzpizzeHyperlink.WindowTitles.Add("Home Page - Pizza Manager");
                    #endregion
                }
                return this.mUIStwórzpizzeHyperlink;
            }
        }
        
        public HtmlHyperlink UIPizzaManagerHyperlink
        {
            get
            {
                if ((this.mUIPizzaManagerHyperlink == null))
                {
                    this.mUIPizzaManagerHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPizzaManagerHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPizzaManagerHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPizzaManagerHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPizzaManagerHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Pizza Manager";
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/";
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "navbar-brand";
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"navbar-brand\" href=\"/\"";
                    this.mUIPizzaManagerHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIPizzaManagerHyperlink.WindowTitles.Add("Home Page - Pizza Manager");
                    #endregion
                }
                return this.mUIPizzaManagerHyperlink;
            }
        }
        
        public HtmlHyperlink UIKontaktHyperlink
        {
            get
            {
                if ((this.mUIKontaktHyperlink == null))
                {
                    this.mUIKontaktHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIKontaktHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIKontaktHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIKontaktHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIKontaktHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Kontakt";
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/Contact";
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Home/Contact";
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/Contact\"";
                    this.mUIKontaktHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIKontaktHyperlink.WindowTitles.Add("Home Page - Pizza Manager");
                    #endregion
                }
                return this.mUIKontaktHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUIStwórzpizzeHyperlink;
        
        private HtmlHyperlink mUIPizzaManagerHyperlink;
        
        private HtmlHyperlink mUIKontaktHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPizzaManagerPizzaManDocument : HtmlDocument
    {
        
        public UIPizzaManagerPizzaManDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "PizzaManager - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pizza/New";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Pizza/New";
            this.WindowTitles.Add("PizzaManager - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINazwaEdit
        {
            get
            {
                if ((this.mUINazwaEdit == null))
                {
                    this.mUINazwaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Pizza_Name";
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Pizza.Name";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwa";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Pizza.Name\" class=\"form-control\" i";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUINazwaEdit.WindowTitles.Add("PizzaManager - Pizza Manager");
                    #endregion
                }
                return this.mUINazwaEdit;
            }
        }
        
        public HtmlEdit UICenaEdit
        {
            get
            {
                if ((this.mUICenaEdit == null))
                {
                    this.mUICenaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICenaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Pizza_Price";
                    this.mUICenaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Pizza.Price";
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Cena";
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Pizza.Price\" class=\"form-control\" ";
                    this.mUICenaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUICenaEdit.WindowTitles.Add("PizzaManager - Pizza Manager");
                    #endregion
                }
                return this.mUICenaEdit;
            }
        }
        
        public HtmlComboBox UIDodatekComboBox
        {
            get
            {
                if ((this.mUIDodatekComboBox == null))
                {
                    this.mUIDodatekComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIDodatekComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "Pizza_DodatekId";
                    this.mUIDodatekComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "Pizza.DodatekId";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Dodatek";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "4";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"Pizza.DodatekId\" class=\"form-contr";
                    this.mUIDodatekComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUIDodatekComboBox.WindowTitles.Add("PizzaManager - Pizza Manager");
                    #endregion
                }
                return this.mUIDodatekComboBox;
            }
        }
        
        public HtmlButton UIZapiszButton
        {
            get
            {
                if ((this.mUIZapiszButton == null))
                {
                    this.mUIZapiszButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Zapisz";
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\"";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIZapiszButton.WindowTitles.Add("PizzaManager - Pizza Manager");
                    #endregion
                }
                return this.mUIZapiszButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINazwaEdit;
        
        private HtmlEdit mUICenaEdit;
        
        private HtmlComboBox mUIDodatekComboBox;
        
        private HtmlButton mUIZapiszButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexPizzaManagerDocument : HtmlDocument
    {
        
        public UIIndexPizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/dodatek";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/dodatek";
            this.WindowTitles.Add("Index - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIStwórznowydodatekHyperlink
        {
            get
            {
                if ((this.mUIStwórznowydodatekHyperlink == null))
                {
                    this.mUIStwórznowydodatekHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIStwórznowydodatekHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIStwórznowydodatekHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIStwórznowydodatekHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIStwórznowydodatekHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Stwórz nowy dodatek ⊛ ";
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Dodatek/New";
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Dodatek/New";
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-success";
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-success\" href=\"/Dodatek/N";
                    this.mUIStwórznowydodatekHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "16";
                    this.mUIStwórznowydodatekHyperlink.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUIStwórznowydodatekHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIStwórznowydodatekHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDodatekFormPizzaManaDocument : HtmlDocument
    {
        
        public UIDodatekFormPizzaManaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "DodatekForm - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Dodatek/New";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Dodatek/New";
            this.WindowTitles.Add("DodatekForm - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINazwaEdit
        {
            get
            {
                if ((this.mUINazwaEdit == null))
                {
                    this.mUINazwaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Dodatek_Name";
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Dodatek.Name";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwa";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Dodatek.Name\" class=\"form-control\"";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUINazwaEdit.WindowTitles.Add("DodatekForm - Pizza Manager");
                    #endregion
                }
                return this.mUINazwaEdit;
            }
        }
        
        public HtmlButton UIStwórzButton
        {
            get
            {
                if ((this.mUIStwórzButton == null))
                {
                    this.mUIStwórzButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Stwórz ⊛";
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-success";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-success\" type=\"submit\"";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUIStwórzButton.WindowTitles.Add("DodatekForm - Pizza Manager");
                    #endregion
                }
                return this.mUIStwórzButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINazwaEdit;
        
        private HtmlButton mUIStwórzButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexPizzaManagerDocument1 : HtmlDocument
    {
        
        public UIIndexPizzaManagerDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Dodatek/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Dodatek/";
            this.WindowTitles.Add("Index - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDeleteHyperlink
        {
            get
            {
                if ((this.mUIDeleteHyperlink == null))
                {
                    this.mUIDeleteHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Delete";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Dodatek/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Dodatek/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Dodatek/Delete/5\"";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mUIDeleteHyperlink.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUIDeleteHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDeleteHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIContactPizzaManagerDocument : HtmlDocument
    {
        
        public UIContactPizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Contact - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/Contact";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Home/Contact";
            this.WindowTitles.Add("Contact - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAboutHyperlink
        {
            get
            {
                if ((this.mUIAboutHyperlink == null))
                {
                    this.mUIAboutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/About\"";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIAboutHyperlink.WindowTitles.Add("Contact - Pizza Manager");
                    #endregion
                }
                return this.mUIAboutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAboutHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAboutPizzaManagerDocument : HtmlDocument
    {
        
        public UIAboutPizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "About - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/About";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Home/About";
            this.WindowTitles.Add("About - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITwojePizzeHyperlink
        {
            get
            {
                if ((this.mUITwojePizzeHyperlink == null))
                {
                    this.mUITwojePizzeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Twoje Pizze";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pizza";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Pizza";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pizza\"";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUITwojePizzeHyperlink.WindowTitles.Add("About - Pizza Manager");
                    #endregion
                }
                return this.mUITwojePizzeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITwojePizzeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexPizzaManagerDocument2 : HtmlDocument
    {
        
        public UIIndexPizzaManagerDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pizza";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Pizza";
            this.WindowTitles.Add("Index - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRegisterHyperlink
        {
            get
            {
                if ((this.mUIRegisterHyperlink == null))
                {
                    this.mUIRegisterHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "registerLink";
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRegisterHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Account/Register";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"registerLink\" href=\"/Account/Registe";
                    this.mUIRegisterHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIRegisterHyperlink.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUIRegisterHyperlink;
            }
        }
        
        public HtmlHyperlink UICarbonAraHyperlink
        {
            get
            {
                if ((this.mUICarbonAraHyperlink == null))
                {
                    this.mUICarbonAraHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICarbonAraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICarbonAraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICarbonAraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICarbonAraHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "CarbonAra";
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pizza/Details/1";
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Pizza/Details/1";
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pizza/Details/1\"";
                    this.mUICarbonAraHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUICarbonAraHyperlink.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUICarbonAraHyperlink;
            }
        }
        
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "h";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = null;
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = null;
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UIPizzaHyperlink
        {
            get
            {
                if ((this.mUIPizzaHyperlink == null))
                {
                    this.mUIPizzaHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPizzaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPizzaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPizzaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPizzaHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "pizza";
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pizza/Details/7";
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Pizza/Details/7";
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pizza/Details/7\"";
                    this.mUIPizzaHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "20";
                    this.mUIPizzaHyperlink.WindowTitles.Add("Index - Pizza Manager");
                    #endregion
                }
                return this.mUIPizzaHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRegisterHyperlink;
        
        private HtmlHyperlink mUICarbonAraHyperlink;
        
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUIPizzaHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRegisterPizzaManagerDocument : HtmlDocument
    {
        
        public UIRegisterPizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Register - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Account/Register";
            this.WindowTitles.Add("Register - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUILoginHyperlink.WindowTitles.Add("Register - Pizza Manager");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILoginHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDetailsPizzaManagerDocument : HtmlDocument
    {
        
        public UIDetailsPizzaManagerDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details - Pizza Manager";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Pizza/Details/1";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:61811/Pizza/Details/1";
            this.WindowTitles.Add("Details - Pizza Manager");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITwojePizzeHyperlink
        {
            get
            {
                if ((this.mUITwojePizzeHyperlink == null))
                {
                    this.mUITwojePizzeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITwojePizzeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Twoje Pizze";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Pizza";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:61811/Pizza";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Pizza\"";
                    this.mUITwojePizzeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUITwojePizzeHyperlink.WindowTitles.Add("Details - Pizza Manager");
                    #endregion
                }
                return this.mUITwojePizzeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITwojePizzeHyperlink;
        #endregion
    }
}
